--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/ImAMadDev/UltimateVote
build-by-default: true
branches:
  - main
projects:
  PermissionEffects:
    path: ""
    icon: "assets/icon.png"
...